lib/my_app_web/router.ex
defmodule MyAppWeb.Router do
  use MyAppWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {MyAppWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MyAppWeb.Authenticator
  end

  pipeline :api do
    plug :accepts, ["json"]
  end


  scope "/", MyAppWeb do
    pipe_through :browser

    # get "/*default_page", PageController, :under_maintenance
    get "/tests", PageController, :test
    get "/", PageController, :index
    get "/about-us", PageController, :about_us
    get "/terms-of-use", PageController, :term_of_use
    get "/privacy-policy", PageController, :privacy_policy
    get "/contact-us", PageController, :contact_us
    get "/data-entries/departments", PageController, :departments
    get "/data-entries/procurements", PageController, :prs
    
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete
  end


  ## PROCUMENT REQUEST ROUTES ##
  scope "/procurements", MyAppWeb.Procurement, as: :pr do
    pipe_through [:browser]

    get "/on-going/requests", AccountController, :ongoing_prs
    post "/on-going/requests", AccountController, :sort_ongoing_prs 

    resources "/requests", AccountController, only: [:new, :show, :create, :edit, :update, :delete]

    resources "/end_users/requests", PageController, only: [:index, :show]

    get "/search", PageController, :search
    post "/search", PageController, :search_pr

    get "/failed/procurement-requests", PageController, :failed_prs
    post "/failed/procurement-requests", PageController, :sort_failed_prs
    get "/succeeded/procurement-requests", PageController, :succeeded_prs
    post "/succeeded/procurement-requests", PageController, :sort_succeeded_prs
    get "/archived/procurement-requests", PageController, :archived_prs
    post "/archived/procurement-requests", PageController, :sort_archived_prs
    get "/generated-reports", PageController, :generated_report
  end


  ## TRANSACTION ROUTES ##
  scope "/transactions", MyAppWeb.Transaction, as: :transaction do
    pipe_through [:browser]

    get "/new/:item_id", PageController, :new_transaction
    get "/active", PageController, :active_transactions
    get "/success", PageController, :success_transactions
    get "/canceled", PageController, :canceled_transactions
    get "/view-transactions/:id", PageController, :view_transaction
    post "/negotiations", PageController, :create_negotiation
    post "/", PageController, :create_transaction
    post "/update/:id", PageController, :update_transaction
  end


  ## USER ROUTES ##

  scope "/users", MyAppWeb.User, as: :user do
    pipe_through [:browser]

    get "/list-purchase-officers", PageController, :list_purchase_officers
    get "/list-budget-officers", PageController, :list_budget_officers
    get "/list-inventory-officers", PageController, :list_inventory_officers

    resources "/", PageController, only: [
      :new, :create, :show, :index
    ]
    get "/personnels/purchaser/new", AccountController, :new_purchaser
    get "/personnels/budget-officer/new", AccountController, :new_budget_officer
    get "/personnels/inventory-officer/new", AccountController, :new_inventory_officer
    
    post "/personnels/purchaser/", AccountController, :create_purchaser
    post "/personnels/budget-officer/", AccountController, :create_budget_officer
    post "/personnels/inventory-officer/", AccountController, :create_inventory_officer
    get "/personnels/:id", AccountController, :index
    get "/accounts/:id", AccountController, :show
  end

  ## Department ROUTES ##
  scope "/departments", MyAppWeb.Company, as: :company do
    pipe_through :browser

    get "/accounts/:id", AccountController, :account
    get "/accounts/:id/edit", AccountController, :edit_account
    put "/accounts", AccountController, :update_account

    get "/accounts/notify/:email", AccountController, :notify_account

    get "/approved-accounts", AccountController, :approved_companies
    get "/unapproved-accounts", AccountController, :unapproved_companies
    post "/approve-accounts/:id", AccountController, :approve_company
    post "/cancel-approvals/:id", AccountController, :disapprove_company

    resources "/", PageController, only: [
      :new, :create, :show, :index, :delete
    ]
   
  end

  ## ITEMS ROUTES ##
  scope "/products-and-services", MyAppWeb.Item, as: :item do
    pipe_through :browser

    post "/items/:id", PageController, :item
    get "/items-to-buy", PageController, :items_to_buy
    get "/items-to-sell", PageController, :items_to_sell
 
    resources "/", PageController, only: [
      :new, :create, :show, :index
    ]
  end


  ## Home ##
  scope "/*home", MyAppWeb do
    pipe_through :browser

    get "/", PageController, :index
  end
  

  # Other scopes may use custom stacks.
  # scope "/api", MyAppWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: MyAppWeb.Telemetry
    end
  end
end

lib/my_app/query/user.ex
defmodule MyApp.Query.User do
  alias MyApp.Schema.User
  alias MyApp.Repo

  import Ecto.Query, warn: false

  @doc """
  New User
  """
  def new_user do
    %User{}
    |> User.changeset_with_password()
  end

  @doc """
  Insert new user
  """
  def insert_user(params) do
    %User{}
    |> User.changeset_with_password(params)
    |> Repo.insert()
  end

  @doc """
  Get user by id
  """
  def get_user(id) do
    query =
      from u in User,
        where: u.id == ^id,
	preload: [:company]

    Repo.one(query)
  end

  @doc """
  List users.
  """
  def list_users do
    Repo.all(User)
  end

  @doc """
  List all purchase officers.
  """
  def list_purchase_officers do
    query =
      from u in User,
        where: u.role == "Purchase",
	preload: [:company]

    Repo.all(query)
  end

  @doc """
  List all budget officers.
  """
  def list_budget_officers do
    query =
      from u in User,
        where: u.role == "Budget",
	preload: [:company]

    Repo.all(query)
  end

  @doc """
  List all inventory officers.
  """
  def list_inventory_officers do
    query =
      from u in User,
        where: u.role == "Inventory",
	preload: [:company]

    Repo.all(query)
  end

  @doc """
  List all users/personnels under company.
  """
  def list_company_personnels(company_id) do
    query =
      from u in User,
        where: u.company_id == ^company_id

    Repo.all(query)
  end

  @doc """
  Get company personnel by role.
  """
  def get_company_personnel_by_role(company_id, role) do
    query =
      from u in User,
        where: u.company_id == ^company_id and u.role == ^role

    Repo.one(query)
  end

  @doc """
  Get user by attribute.
  """
  def get_user_by(params) do
    Repo.get_by(User, params)
  end

  @doc """
  Get user by email and password.
  """
  def get_user_by_email_and_password(email, password) do
    with user when not is_nil(user) <- get_user_by(%{email: String.trim(email)}),
         true <- MyApp.Password.verify_with_hash(password, user.hashed_password),
         true <- user.is_verified do
      user
    else
      _ -> MyApp.Password.dummy_verify
    end
  end
end

lib/my_app/schema/user.ex
defmodule MyApp.Schema.User do
  use Ecto.Schema
  import Ecto.Changeset


  schema "users" do
    belongs_to :company, MyApp.Schema.Company
    has_many :transaction, MyApp.Schema.Transaction
    field(:fullname, :string)
    field(:role, :string)
    field(:email, :string)
    field(:password, :string, virtual: true)
    field(:hashed_password, :string)
    field(:is_verified, :boolean, default: false)
    field(:deactivated, :boolean, default: false)  
    timestamps(type: :utc_datetime_usec)
  end


  @allowed_fields [
    :company_id,
    :fullname,
    :role,
    :email,
    :hashed_password,
    :is_verified,
    :deactivated
  ]


  @required_fields @allowed_fields


  @doc false
  def changeset(user, params \\ %{}) do
    user
    |> cast(params, @allowed_fields)
    |> validate_required(@required_fields)
    |> validate_format(:email, ~r/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/)
    |> unique_constraint(:email)
  end


  def changeset_with_password(user, params \\ %{}) do
    user
    |> cast(params, [:password])
    |> validate_required(:password)
    |> validate_length(:password, min: 6)
    |> validate_confirmation(:password, required: true)
    |> hash_password()
    |> changeset(params)
  end


  defp hash_password(%Ecto.Changeset{changes: %{password: password}} = changeset) do
    changeset
    |> put_change(:hashed_password, MyApp.Password.hash(password))
  end

  defp hash_password(changeset), do: changeset
end

lib/my_app_web/controllers/user/account_controller.ex
defmodule MyAppWeb.User.AccountController do
  use MyAppWeb, :controller

  alias MyApp.Query.User

  def show(conn, %{"id" => id}) do
    user = User.get_user(id)
    render(conn, :show, user: user)
  end

  def index(conn, %{"id" => company_id}) do
    purchase = User.get_company_personnel_by_role(company_id, "Purchase")
    budget = User.get_company_personnel_by_role(company_id, "Budget")
    inventory = User.get_company_personnel_by_role(company_id, "Inventory")
    params = [
      purchase: purchase,
      budget: budget,
      inventory: inventory
    ]
    render(conn, :index, params)
  end

  def new_purchaser(conn, _params) do
    user = User.new_user()
    render(conn, "new-purchaser.html", user: user)
  end

  def new_budget_officer(conn, _params) do
    user = User.new_user()
    render(conn, "new-budget-officer.html", user: user)
  end

  def new_inventory_officer(conn, _params) do
    user = User.new_user()
    render(conn, "new-inventory-officer.html", user: user)
  end

  def create_purchaser(conn, %{"user" => params}) do
    company_id = conn.assigns.current_company.id
    params = Map.put(params, "company_id", company_id)
    |> Map.put("role", "Purchase")
    |> Map.put("is_verified", true)
    
    case User.insert_user(params) do
      {:ok, _user} ->
        conn
	|> put_flash(:info, "Purchase Officer account was added successfully.")
	|> redirect(to: Routes.user_account_path(conn, :index, company_id))
      {:error, %Ecto.Changeset{} = user} ->
        conn
	|> render("new-purchaser.html", user: user)
    end
  end


  def create_budget_officer(conn, %{"user" => params}) do
    company_id = conn.assigns.current_company.id
    params = Map.put(params, "company_id", company_id)
    |> Map.put("role", "Budget")
    |> Map.put("is_verified", true)

    case User.insert_user(params) do
      {:ok, _user} ->
        conn
        |> put_flash(:info, "Budget Officer account was added successfully.")
        |> redirect(to: Routes.user_account_path(conn, :index, company_id))
      {:error, %Ecto.Changeset{} = user} ->
        conn
        |> render("new-budget-officer.html", user: user)
    end
  end

  def create_inventory_officer(conn, %{"user" => params}) do
    company_id = conn.assigns.current_company.id
    params = Map.put(params, "company_id", company_id)
    |> Map.put("role", "Inventory")
    |> Map.put("is_verified", true)

    case User.insert_user(params) do
      {:ok, _user} ->
        conn
        |> put_flash(:info, "Inventory Officer account was added successfully.")
        |> redirect(to: Routes.user_account_path(conn, :index, company_id))
      {:error, %Ecto.Changeset{} = user} ->
        conn
        |> render("new-inventory-officer.html", user: user)
    end
  end
end

lib/my_app_web/controllers/user/page_controller.ex
defmodule MyAppWeb.User.PageController do
  use MyAppWeb, :controller

  alias MyApp.Query.{User, Transaction}

  def list_purchase_officers(conn, _params) do
    purchase_officers = User.list_purchase_officers()
    params = [
      purchase_officers: purchase_officers
    ]
    render(conn, "purchase-officers.html", params)
  end

  def list_budget_officers(conn, _params) do
    budget_officers = User.list_budget_officers()
    params = [
      budget_officers: budget_officers
    ]
    render(conn, "budget-officers.html", params)
  end

  def list_inventory_officers(conn, _params) do
    inventory_officers = User.list_inventory_officers()
    params = [
      inventory_officers: inventory_officers
    ]
    render(conn, "inventory-officers.html", params)
  end

  def index(conn, _params) do
    purchase_officers = User.list_purchase_officers()
    budget_officers = User.list_budget_officers()
    inventory_officers = User.list_inventory_officers()
    params = [
      purchase_officers: purchase_officers,
      budget_officers: budget_officers,
      inventory_officers: inventory_officers
    ]
    render(conn, :index, params)
  end

  def new(conn, _params) do
    user = User.new_user()
    render(conn, :new, user: user)
  end

  def create(conn, %{"user" => %{"first_name" => first_name, "middle_name" => middle_name, "last_name" => last_name, "email" => email, "gender" => gender, "birth_date" => birth_date, "about_me" => about_me, "password" => password, "password_confirmation" => password_confirmation} = params}) do
    case User.insert_user(params) do
      {:ok, _user} ->
        conn
	|> put_flash(:info, "New User added")
	|> redirect(to: Routes.page_path(conn, :index))
      {:error, %Ecto.Changeset{} = user} ->
        conn
	|> render(:new, user: user)
    end
  end

  def show(conn, %{"id" => id}) do
    user = User.get_user(id)
    cond do
      user == nil ->
        conn
	|> redirect(to: Routes.page_path(conn, :index))
      user.role == "Purchase" ->
        active_transactions = Transaction.list_purchase_officer_active_transactions(user)
	canceled_transactions = Transaction.list_purchase_officer_canceled_transactions(user)
	success_transactions = Transaction.list_purchase_officer_success_transactions(user)
	params = [
	  active_transactions: active_transactions,
	  canceled_transactions: canceled_transactions,
	  success_transactions: success_transactions
	]
        render(conn, :show, params)
      user.role == "Budget" ->
        active_transactions = Transaction.list_budget_officer_active_transactions(user)
        canceled_transactions = Transaction.list_budget_officer_canceled_transactions(user)
        success_transactions = Transaction.list_budget_officer_success_transactions(user)
        params = [
          active_transactions: active_transactions,
          canceled_transactions: canceled_transactions,
          success_transactions: success_transactions
        ]
        render(conn, :show, params)
      user.role == "Inventory" ->
        active_transactions = Transaction.list_inventory_officer_active_transactions(user)
        canceled_transactions = Transaction.list_inventory_officer_canceled_transactions(user)
        success_transactions = Transaction.list_inventory_officer_success_transactions(user)
        params = [
          active_transactions: active_transactions,
          canceled_transactions: canceled_transactions,
          success_transactions: success_transactions
        ]
        render(conn, :show, params)
      true ->
        conn
	|> redirect(to: Routes.page_path(conn, :index))
    end
  end
end

lib/my_app_web/views/user/account_view.ex
defmodule MyAppWeb.User.AccountView do
  use MyAppWeb, :view

end

lib/my_app_web/views/user/page_view.ex
defmodule MyAppWeb.User.PageView do
  use MyAppWeb, :view

end

lib/my_app_web/templates/user/page/budget-officers.html.eex
<%= render(MyAppWeb.SharedView, "top-nav.html", conn: @conn) %>

<div class="sub-container">
  <div class="pc-content-container">
    <%= render(MyAppWeb.SharedView, "side-menu.html", conn: @conn) %>
    <div class="pc-content">
      <p class="page-titles">Budget Officers</p>
      <%= if @budget_officers == [] do %>
      <br />
      <p align="center">No Records Yet</p>
      <% else %>
      <table>
        <thead>
          <tr>
            <th>Fullname</th>
            <th>Email</th>
            <th>Company</th>
          </tr>
        </thead>
        <tbody>
          <%= for budget_officer <- @budget_officers do %>
              <tr>
                <td><%= budget_officer.fullname %></td>
                <td><%= budget_officer.email %></td>
                <td><%= budget_officer.company.name %></td>
              </tr>
              <% end %>
        </tbody>
      </table>
      <% end %>
    </div>
  </div>
</div>

lib/my_app_web/templates/user/page/index.html.eex
<%= render(MyAppWeb.SharedView, "top-nav.html", conn: @conn) %>

<div id="page-content-container">

  <!-- side menu for large devices -->
  <%= render(MyAppWeb.SharedView, "side-menu.html", conn: @conn) %>

  <div class="sub-container">
    <div class="pc-content-container">
      <div class="page-content">
	<p class="page-titles">Personnels</p>
	
	<div class="company-logos-container">
	  <a href="<%= Routes.user_page_path(@conn, :list_purchase_officers) %>">
	    <div class="company-logo-container">
	      <img src="/images/personnel.png"/>
	      <p>Purchase Officers: <%= length(@purchase_officers) %></p>
	    </div>
	  </a>
	  <a href="<%= Routes.user_page_path(@conn, :list_budget_officers) %>">
	    <div class="company-logo-container">
	      <img src="/images/personnel.png"/>
	      <p>Budget Officers: <%= length(@budget_officers) %></p>
	    </div>
	  </a>
	  <a href="<%= Routes.user_page_path(@conn, :list_inventory_officers) %>">
	    <div class="company-logo-container">
	      <img src="/images/personnel.png"/>
	      <p>Inventory Officers: <%= length(@inventory_officers) %></p>
	    </div>
	  </a>
	</div>
      </div>
    </div>
    <!-- footer -->
    <%= render(MyAppWeb.SharedView, "footer.html", conn: @conn) %>
  </div>
</div>

lib/my_app_web/templates/user/page/inventory-officers.html.eex
<%= render(MyAppWeb.SharedView, "top-nav.html", conn: @conn) %>

<div class="sub-container">
  <div class="pc-content-container">
    <%= render(MyAppWeb.SharedView, "side-menu.html", conn: @conn) %>
    <div class="pc-content">
      <p class="page-titles">Inventory Officers</p>
      <%= if @inventory_officers == [] do %>
      <br />
      <p align="center">No Records Yet</p>
      <% else %>
      <table>
        <thead>
          <tr>
            <th>Fullname</th>
            <th>Email</th>
            <th>Company</th>
          </tr>
        </thead>
        <tbody>
          <%= for inventory_officer <- @inventory_officers do %>
              <tr>
                <td><%= inventory_officer.fullname %></td>
                <td><%= inventory_officer.email %></td>
                <td><%= inventory_officer.company.name %></td>
              </tr>
              <% end %>
        </tbody>
      </table>
      <% end %>
    </div>
  </div>
</div>

lib/my_app_web/templates/user/page/new.html.eex
<div class="container">
<%= form_for @user, Routes.user_page_path(@conn, :create), fn f -> %>

<%= if @user.action do %>
<div class="alert alert-danger">
<p>Something went wrong. Please check the errors below</p>
</div>
<% end %>

<label>First Name</label>
<%= text_input f, :first_name, placeholder: "Enter your first name.." %>
<%= error_tag f, :first_name %>

<label>Middle name</label>
<%= text_input f, :middle_name, placeholder: "Enter your middle name.." %>
<%= error_tag f, :middle_name %>

<label>Last name</label>
<%= text_input f, :last_name, placeholder: "Enter your last name.." %>
<%= error_tag f, :last_name %>

<label>Email</label>
<%= email_input f, :email, placeholder: "ex. johndoe@gmail.com" %>
<%= error_tag f, :email %>

<label>Gender</label>
  <%= select f, :gender, [
      "Male": "Male",
      "Female": "Female",
      "Others": "Others"
      ], prompt: "Select Your Gender" %>
  <%= error_tag f, :gender %>

<label>Birth date</label>
  <%= date_select f, :birth_date, year: [options: 1940..current_year()], builder: fn b -> %>
  <%= b.(:day, prompt: "Day") %> /
  <%= b.(:month, prompt: "Month") %> /
  <%= b.(:year, prompt: "Year") %>
  <% end %>
  <%= error_tag f, :birth_date %>

<label>Create password</label>
<%= password_input f, :password, placeholder: "Atleast 6 characters.." %>
<%= error_tag f, :password %>

<label>Confirm password</label>
<%= password_input f, :password_confirmation, placeholder: "Re-type your password.." %>
<%= error_tag f, :password_confirmation %>

<label>Describe yourself</label>
<%= textarea f, :about_me, placeholder: "Say something about yourself.." %>
<%= error_tag f, :about_me %>


<%= submit "Create Account" %>

<% end %>


</div>

lib/my_app_web/templates/user/page/purchase-officers.html.eex
<%= render(MyAppWeb.SharedView, "top-nav.html", conn: @conn) %>

<div class="sub-container">
  <div class="pc-content-container">
    <%= render(MyAppWeb.SharedView, "side-menu.html", conn: @conn) %>
    <div class="pc-content">
      <p class="page-titles">Purchase Officers</p>
      <%= if @purchase_officers == [] do %>
      <br />
      <p align="center">No Records Yet</p>
      <% else %>
      <table>
	<thead>
	  <tr>
	    <th>Fullname</th>
	    <th>Email</th>
	    <th>Company</th>
	  </tr>
	</thead>
	<tbody>
	  <%= for purchase_officer <- @purchase_officers do %>
	      <tr>
		<td><%= purchase_officer.fullname %></td>
		<td><%= purchase_officer.email %></td>
		<td><%= purchase_officer.company.name %></td>
	      </tr>
	      <% end %>
	</tbody>
      </table>
      <% end %>
    </div>
  </div>
</div>

      

lib/my_app_web/templates/user/page/show.html.eex
<%= render(MyAppWeb.SharedView, "top-nav.html", conn: @conn) %>

<div class="sub-container">
  <div class="pc-content-container">
    <%= render(MyAppWeb.SharedView, "side-menu.html", conn: @conn) %>
    <div class="pc-content">
      <p class="page-titles">Transactions</p>
      <%= render(MyAppWeb.SharedView, "flash-messages.html", conn: @conn) %>
      <div class="items-container">
        <a href="<%= Routes.transaction_page_path(@conn, :active_transactions) %>">
          <div class="item">Active - <%= length(@active_transactions) %></div>
        </a>
	<a href="<%= Routes.transaction_page_path(@conn, :canceled_transactions) %>">
          <div class="item">Canceled - <%= length(@canceled_transactions) %></div>
        </a>
	<a href="<%= Routes.transaction_page_path(@conn, :success_transactions) %>">
          <div class="item">Sucess - <%= length(@success_transactions) %></div>
        </a>
      </div>
    </div>
  </div>
</div>