lib/my_app_web/router.ex
defmodule MyAppWeb.Router do
  use MyAppWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {MyAppWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MyAppWeb.Authenticator
  end

  pipeline :api do
    plug :accepts, ["json"]
  end


  scope "/", MyAppWeb do
    pipe_through :browser

    # get "/*default_page", PageController, :under_maintenance
    get "/tests", PageController, :test
    get "/", PageController, :index
    get "/about-us", PageController, :about_us
    get "/terms-of-use", PageController, :term_of_use
    get "/privacy-policy", PageController, :privacy_policy
    get "/contact-us", PageController, :contact_us
    get "/data-entries/departments", PageController, :departments
    get "/data-entries/procurements", PageController, :prs
    
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete
  end


  ## PROCUMENT REQUEST ROUTES ##
  scope "/procurements", MyAppWeb.Procurement, as: :pr do
    pipe_through [:browser]

    get "/on-going/requests", AccountController, :ongoing_prs
    post "/on-going/requests", AccountController, :sort_ongoing_prs 

    resources "/requests", AccountController, only: [:new, :show, :create, :edit, :update, :delete]

    resources "/end_users/requests", PageController, only: [:index, :show]

    get "/search", PageController, :search
    post "/search", PageController, :search_pr

    get "/failed/procurement-requests", PageController, :failed_prs
    post "/failed/procurement-requests", PageController, :sort_failed_prs
    get "/succeeded/procurement-requests", PageController, :succeeded_prs
    post "/succeeded/procurement-requests", PageController, :sort_succeeded_prs
    get "/archived/procurement-requests", PageController, :archived_prs
    post "/archived/procurement-requests", PageController, :sort_archived_prs
    get "/generated-reports", PageController, :generated_report
  end


  ## TRANSACTION ROUTES ##
  scope "/transactions", MyAppWeb.Transaction, as: :transaction do
    pipe_through [:browser]

    get "/new/:item_id", PageController, :new_transaction
    get "/active", PageController, :active_transactions
    get "/success", PageController, :success_transactions
    get "/canceled", PageController, :canceled_transactions
    get "/view-transactions/:id", PageController, :view_transaction
    post "/negotiations", PageController, :create_negotiation
    post "/", PageController, :create_transaction
    post "/update/:id", PageController, :update_transaction
  end


  ## USER ROUTES ##

  scope "/users", MyAppWeb.User, as: :user do
    pipe_through [:browser]

    get "/list-purchase-officers", PageController, :list_purchase_officers
    get "/list-budget-officers", PageController, :list_budget_officers
    get "/list-inventory-officers", PageController, :list_inventory_officers

    resources "/", PageController, only: [
      :new, :create, :show, :index
    ]
    get "/personnels/purchaser/new", AccountController, :new_purchaser
    get "/personnels/budget-officer/new", AccountController, :new_budget_officer
    get "/personnels/inventory-officer/new", AccountController, :new_inventory_officer
    
    post "/personnels/purchaser/", AccountController, :create_purchaser
    post "/personnels/budget-officer/", AccountController, :create_budget_officer
    post "/personnels/inventory-officer/", AccountController, :create_inventory_officer
    get "/personnels/:id", AccountController, :index
    get "/accounts/:id", AccountController, :show
  end

  ## Department ROUTES ##
  scope "/departments", MyAppWeb.Company, as: :company do
    pipe_through :browser

    get "/accounts/:id", AccountController, :account
    get "/accounts/:id/edit", AccountController, :edit_account
    put "/accounts", AccountController, :update_account

    get "/accounts/notify/:email", AccountController, :notify_account

    get "/approved-accounts", AccountController, :approved_companies
    get "/unapproved-accounts", AccountController, :unapproved_companies
    post "/approve-accounts/:id", AccountController, :approve_company
    post "/cancel-approvals/:id", AccountController, :disapprove_company

    resources "/", PageController, only: [
      :new, :create, :show, :index, :delete
    ]
   
  end

  ## ITEMS ROUTES ##
  scope "/products-and-services", MyAppWeb.Item, as: :item do
    pipe_through :browser

    post "/items/:id", PageController, :item
    get "/items-to-buy", PageController, :items_to_buy
    get "/items-to-sell", PageController, :items_to_sell
 
    resources "/", PageController, only: [
      :new, :create, :show, :index
    ]
  end


  ## Home ##
  scope "/*home", MyAppWeb do
    pipe_through :browser

    get "/", PageController, :index
  end
  

  # Other scopes may use custom stacks.
  # scope "/api", MyAppWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: MyAppWeb.Telemetry
    end
  end
end

lib/my_app_web/views/shared_view.ex
defmodule MyAppWeb.SharedView do
  use MyAppWeb, :view

  alias MyApp.Query.Company

  @doc """
  Function to get the number of newly registers that are not seen yet by admin.
  """
  def get_new_registers do
    Company.new_registers
  end

  def get_number_of_pr_updates_for_user(user_id) do
    prs = Company.get_company_with_procurement_request(user_id)
    result = 
    for pr <- prs.procurement_request do
      pr.update_count
    end

    Enum.sum(result)
  end
end

lib/my_app_web/templates/shared/flash-messages.html.eex
<div class="alert-msg">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
</div>

lib/my_app_web/templates/shared/footer.html.eex
<!-- footer -->
<div class="footer">
  <div id="opms-logo">
    <img src="/images/opms-logo.png" alt="Logo"/>
  </div>

  <p class="footer-company-name">Southern Leyte State University</p>

  <div class="footer-options">
    <div><%= link "Contact Us", to: Routes.page_path(@conn, :contact_us) %></div>
    <div><%= link "Terms Of Use", to: Routes.page_path(@conn, :term_of_use) %></div>
    <div><%= link "Privacy Policy", to: Routes.page_path(@conn, :privacy_policy) %></div>
    <div><%= link "About Us", to: Routes.page_path(@conn, :about_us) %></div>
  </div>

  <div class="copyright">
    <p>Copyright &copy; <%= current_year() %> <%= app_name() %><p>
    <p>All rights reserved.</p>
  </div>
</div>

lib/my_app_web/templates/shared/menu-top.html.eex
<div class="menu-top">
    <a href="#" class="nav-btn-top">News<sup class="popup-notice">9+</sup></a>
    <a href="#" class="nav-btn-top">Pages<sup class="popup-otice">9+</sup></a>
    <a href="#" class="nav-btn-top">Shop<sup class="popup-notice">9+</sup></a>
    <a href="#" class="nav-btn-top">Bank<sup class="popup-notice">9+</sup></a>
    <a href="#" class="nav-btn-top">Chat<sup class="popup-notice">9+</sup></a>
    <a href="#" class="nav-btn-top">Menu<sup class="popup-notice">9+</sup></a>
    </div>

lib/my_app_web/templates/shared/pc-template.html.eex
<nav>
  <div id="pcu-logo">
    <img src="/images/opms-logo.png"/>
  </div>
  <div id="schoolname">Online Procurement Monitoring System
  <p id="tagname">Simple, Safe, Effecient E-Procurement Transactions</p></div>
  <div class="menus">
    <li><a href="<%= Routes.session_path(@conn, :new) %>">LOG IN</a></li>
    <li><a href="<%= Routes.company_page_path(@conn, :new) %>">SIGN UP</a></li>
  </div>
</nav>

<div class="sub-container">
  <div class="pc-content-container">
    <div class="side-menu-container">
      <div><%= link "COMPANIES", to: Routes.company_page_path(@conn, :index) %></div>
      <div><a href="#">Users</a></div>
      <div><a href="#">ITEMS</a></div>
    </div>
    <div class="pc-content">
      <h1><%= @company.name %></h1>
    </div>
  </div>
</div>

lib/my_app_web/templates/shared/prs.html.eex
<%= cond do %>
<% @sorted_prs == "" && @prs == [] -> %>
<br>
<p style="margin-left:26rem;">No Records Available Yet!</p>

<% @sorted_prs == "" && @prs != [] -> %>
<table>
  <thead>
    <tr>
      <th>PR_No.</th>
      <th>Department</th>
      <th>End_User</th>
      <th>Purpose</th>
      <th>Date_Needed</th>
      <th>Created</th>
      <th>Updated</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <%= for pr <- @prs do %>
        <tr>
          <td><%= pr.pr_number %></td>
          <td><%= pr.company.department %></td>
          <td><%= pr.end_user %></td>
          <td><%= pr.purpose %></td>
          <th><%= get_date(pr.date_needed) %></th>
          <td><%= get_date(pr.inserted_at) %></td>
          <td><%= get_datetime(pr.updated_at) %></td>
	  <td><span class="<%= get_css_class(pr.status) %>"><%= pr.status %></span></td>
	  <td><a class="statuses blue" href="<%= Routes.pr_account_path(@conn, :show, pr.id) %>">View&nbsp;Details</a></td>
	</tr>
        <% end %>
  </tbody>
</table>
<% @sorted_prs == [] || @sorted_prs == nil -> %>
<br>
<p style="margin-left:26rem;">No Records Available.</p>
<% @sorted_prs != [] -> %>
<table>
  <thead>
    <tr>
      <th>PR_No.</th>
      <th>Department</th>
      <th>End_User</th>
      <th>Purpose</th>
      <th>Date_Needed</th>
      <th>Created</th>
      <th>Updated</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <%= for pr <- @sorted_prs do %>
        <tr>
          <td><%= pr.pr_number %></td>
          <td><%= pr.company.department %></td>
          <td><%= pr.end_user %></td>
          <td><%= pr.purpose %></td>
          <th><%= get_date(pr.date_needed) %></th>
          <td><%= get_date(pr.inserted_at) %></td>
          <td><%= get_datetime(pr.updated_at) %></td>
          <td><span class="<%= get_css_class(pr.status) %>"><%= pr.status %></span></td>
          <td><a class="statuses blue" href="<%= Routes.pr_account_path(@conn, :show, pr.id) %>">View&nbsp;Details</a></td>
        </tr>
        <% end %>
  </tbody>
</table>
<% true -> %>
<br>
<p style="margin-left:26rem;">Something went wrong.</p>    
    
<% end %>

lib/my_app_web/templates/shared/side-menu.html.eex
<div id="side-bar-menu">
  <%= cond do %>
  <% @conn.assigns.current_company != nil and @conn.assigns.current_company.is_admin == true -> %>
  <div class="side-menu-container">
    <div class="a"><i class="fa fa-user"></i><a href="<%= Routes.company_account_path(@conn, :account, @conn.assigns.current_company.id) %>">Admin Account</a></div>
    <div class="a"><i class="fa fa-home"></i><%= link "Home", to: Routes.page_path(@conn, :index) %></div>
    <div class="a"><i class="fa fa-users"></i><%= link "Users", to: Routes.company_page_path(@conn, :index) %>
      <%= if get_new_registers() > 0 do %>
      <sup class="user-notif"><%= get_new_registers() %></sup>
      <% end %>
    </div>
    
    <div id="lsidepr" class="a"><i class="fa fa-file"></i><a href="<%= Routes.pr_account_path(@conn, :ongoing_prs) %>">Procurements</a>
    </div>
    <div class="a"><i class="fa fa-file"></i><%= link "Generate Report", to: Routes.pr_page_path(@conn, :generated_report) %></div>
    <!--
      <div id="lsideprcontainer" class="clsideprcontainer hide">
	<a href="<%= Routes.pr_page_path(@conn, :succeeded_prs) %>">Completed &gt;</a>
	<a href="<%= Routes.pr_page_path(@conn, :failed_prs) %>">Failed    &gt;</a>
      </div>
    -->
    <div class="a"><i class="fa fa-info-circle"></i><%= link "About us", to: Routes.page_path(@conn, :about_us) %></div>

    <div class="a"><i class="fa fa-address-book"></i><%= link "Contact us", to: Routes.page_path(@conn, :contact_us) %></div>

    <div class="a"><i class="fa fa-legal"></i><%= link "Terms of use", to: Routes.page_path(@conn, :term_of_use) %></div>

    <div class="a"><i class="fa fa-lock"></i><%= link "Privacy policy", to: Routes.page_path(@conn, :privacy_policy) %></div>

    <div class="a"><i class="fa fa-sign-out"></i><%= link "Log out", to: Routes.session_path(@conn, :delete), method: :delete, data: [confirm: "Are you sure?"] %></div>
  </div>

  <% @conn.assigns.current_company != nil && @conn.assigns.current_company.is_admin == false -> %>

  <div class="side-menu-container">
    <div class="a"><i class="fa fa-user"></i><a href="<%= Routes.company_account_path(@conn, :account, @conn.assigns.current_company.id) %>">My Account</a></div>
    <div class="a"><i class="fa fa-home"></i><%= link "Home", to: Routes.page_path(@conn, :index) %></div>
    <div class="a"><i class="fa fa-file"></i><%= link "Procurements", to: Routes.pr_page_path(@conn, :index, id: @conn.assigns.current_company.id) %>
      <%= if get_number_of_pr_updates_for_user(@conn.assigns.current_company.id) > 0 do %>              <sup class="user-notif">
	<%= get_number_of_pr_updates_for_user(@conn.assigns.current_company.id) %></sup>
      <% end %>
    </div>
    <div class="a"><i class="fa fa-info-circle"></i><%= link "About us", to: Routes.page_path(@conn, :about_us) %></div>
    <div class="a"><i class="fa fa-address-book"></i><%= link "Contact us", to: Routes.page_path(@conn, :contact_us) %></div>
    <div class="a"><i class="fa fa-legal"></i><%= link "Terms of use", to: Routes.page_path(@conn, :term_of_use) %></div>
    <div class="a"><i class="fa fa-lock"></i><%= link "Privacy policy", to: Routes.page_path(@conn, :privacy_policy) %></div>
    <div class="a"><i class="fa fa-sign-out"></i><%= link "Log out", to: Routes.session_path(@conn, :delete), method: :delete, data: [confirm: "Are you sure?"] %></div>
  </div>

  <% true -> %>

  <div class="side-menu-container">
    <div class="a"><i class="fa fa-home"></i><%= link "Home", to: Routes.page_path(@conn, :index) %></div>
    <div class="a"><i class="fa fa-info-circle"></i><%= link "About us", to: Routes.page_path(@conn, :about_us) %></div>
    <div class="a"><i class="fa fa-address-book"></i><%= link "Contact us", to: Routes.page_path(@conn, :contact_us) %></div>
    <div class="a"><i class="fa fa-legal"></i><%= link "Terms of use", to: Routes.page_path(@conn, :term_of_use) %></div>
    <div class="a"><i class="fa fa-lock"></i><%= link "Privacy policy", to: Routes.page_path(@conn, :privacy_policy) %></div>
    <div class="a"><i class="fa fa-user-plus"></i><%= link "Register", to: Routes.company_page_path(@conn, :new) %></div>
    <div class="a"><i class="fa fa-sign-in"></i><%= link "Log in", to: Routes.session_path(@conn, :new) %></div>
  </div>
  <% end %>
</div>

lib/my_app_web/templates/shared/sm-menu.html.eex
<div class="sm-menu">
  <div><i class="fa fa-arrow-left" onclick="back();"></i></div>
  <div class="back-nav-title"><%= @title %></div>
  <div id="openNav" onclick="opennav();" class="back-nav-menu"><i class="fa fa-bars"></i></div>
</div>

<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" onclick="closenav();" class="closebtn" id="closeNav">&times;</a>

  <%= if @conn.assigns.current_company != nil and @conn.assigns.current_company.is_admin == true do %>
  <a href="<%= Routes.company_account_path(@conn, :account, @conn.assigns.current_company.id) %>"><i class="fa fa-user"></i>&nbsp;&nbsp;Admin Account</a>
  <a href="<%= Routes.company_page_path(@conn, :index) %>"><i class="fa fa-users"></i>&nbsp;&nbsp;Users</a>
  <a href="<%= Routes.pr_account_path(@conn, :ongoing_prs) %>"><i class="fa fa-file"></i>&nbsp;&nbsp;Procurements</a>
  <a href="<%= Routes.page_path(@conn, :about_us) %>"><i class="fa fa-info-circle"></i>&nbsp;&nbsp;About us</a>
  <a href="<%= Routes.page_path(@conn, :contact_us) %>"><i class="fa fa-address-book"></i>&nbsp;&nbsp;Contact us</a>
  <a href="<%= Routes.page_path(@conn, :term_of_use) %>"><i class="fa fa-legal"></i>&nbsp;&nbsp;Terms of use</a>
  <a href="<%= Routes.page_path(@conn, :privacy_policy) %>"><i class="fa fa-lock"></i>&nbsp;&nbsp;Privacy policy</a>
  <%= link "Log out", to: Routes.session_path(@conn, :delete), method: :delete, data: [confirm: "Are you sure?"] %>
  <% end %>
  
  <%= if @conn.assigns.current_company != nil && @conn.assigns.current_company.is_admin != true do %>
  <!-- non admin users -->
  <a href="<%= Routes.company_account_path(@conn, :account, @conn.assigns.current_company.id) %>"><i class="fa fa-user"></i>&nbsp;&nbsp;My Account</a>
    <a href="<%= Routes.pr_page_path(@conn, :index, id: @conn.assigns.current_company.id) %>"><i class="fa fa-file"></i>&nbsp;&nbsp;Procurements</a>
    <a href="<%= Routes.page_path(@conn, :about_us) %>"><i class="fa fa-info-circle"></i>&nbsp;&nbsp;About us</a>

    <a href="<%= Routes.page_path(@conn, :contact_us) %>"><i class="fa fa-address-book"></i>&nbsp;&nbsp;Contact us</a>

    <a href="<%= Routes.page_path(@conn, :term_of_use) %>"><i class="fa fa-legal"></i>&nbsp;&nbsp;Terms of use</a>

    <a href="<%= Routes.page_path(@conn, :privacy_policy) %>"><i class="fa fa-lock"></i>&nbsp;&nbsp;Privacy policy</a>

    <%= link "Log out", to: Routes.session_path(@conn, :delete), method: :delete, data: [confirm: "Are you sure?"] %>
    
  <% end %>

  <%= if @conn.assigns.current_company == nil do %>
  <a href="<%= Routes.page_path(@conn, :index) %>"><i class="fa fa-home"></i>&nbsp;&nbsp;Home</a>
  <a href="<%= Routes.page_path(@conn, :about_us) %>"><i class="fa fa-info-circle"></i>&nbsp;&nbsp;About us</a>
  <a href="<%= Routes.page_path(@conn, :contact_us) %>"><i class="fa fa-address-book"></i>&nbsp;&nbsp;Contact us</a>
  <a href="<%= Routes.page_path(@conn, :term_of_use) %>"><i class="fa fa-legal"></i>&nbsp;&nbsp;Terms of use</a>
  <a href="<%= Routes.page_path(@conn, :privacy_policy) %>"><i class="fa fa-lock"></i>&nbsp;&nbsp;Privacy policy</a>
  <a href="<%= Routes.session_path(@conn, :new) %>"><i class="fa fa-sign-in"></i>&nbsp;&nbsp;Sign in</a>
  <% end %>
</div>

lib/my_app_web/templates/shared/top-nav.html.eex
<nav id="nav">
  <div class="logo-name-container">
    <div id="pcu-logo">
      <img src="/images/opms-logo.png"/>
    </div>
    <div id="schoolname">Southern Leyte State University
      <p id="tagname">Online Procurement Monitoring System</p>
    </div>
  </div>
</nav>